version: "3"
services:
    self-signed-certificate-generator:
        build:
            context: ../
            dockerfile: Dockerfile
        image: magnitus/certificate-generator:latest
        environment:
            COUNTRY: CA
            STATE: Quebec
            CITY: Montreal
            ORGANIZATION: Any
            DEPARTMENT: IT
            EMAIL: email@mydomain.com
            DOMAINS: dev.mydomain.com;test.mydomain.com
            CERTIFICATE_DURATION: 1095
            KEY_FILE: ""
            CSR_FILE: ""
            CERTIFICATE_FILE: ""
            OUTPUT_CERTIFICATE_INFO: "true"
        volumes:
            - .:/opt/output
            - ./password.txt:/opt/password.txt
