app:
  container_name: build-image-example2-slim
  image: magnitus/node-app:image-builder
  environment:
    - SOURCE_IMAGE=magnitus/node-app:6-slim
    - UID=1000
    - OUTPUT_IMAGE=magnitus/node-app:image-builder-example2-slim
    - IGNORE=.+~$$
    - EXTERNAL_PORT=8080
    - DOCKER_LOCALHOST=172.17.0.1
    - CACHE=no
    - NPM_COMMAND=test
  volumes:
    - ./app:/opt/app
    - ./shared:/opt/shared
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "8080:8080"
